app = "game-server-uro"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PHX_HOST = "game-server-uro.fly.dev"
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = start
  auto_start_machines = start
  min_machines_running = 1
  max_machines_running = 1
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
