app = "game-server-uro"
primary_region = "ams"

[build]
  image = "ghcr.io/appsinacup/game_server:latest"

[env]
  PORT = "4000"
  SQLITE_DATABASE_PATH = "/data/game_server_prod.db"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    interval = "30s"
    timeout = "15s"
    grace_period = "30s"
    method = "GET"
    path = "/api/v1/health"

[[vm]]
  size = "shared-cpu-1x"

[[mounts]]
  source = "game_server_data"
  destination = "/data"
